# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hcs8bGm6GdfmKIvTEtt23LQuZKWA6sQr
"""

# Simple Python app to accept name input and display it

def greet_user():
    # Get user's name
    name = input("Please enter your name: ")

    # Display a greeting with the user's name
    print(f"Hello, {name}! Welcome to the app.")

# Call the function to run the app
greet_user()